### ISSUE TITLE
WYSIWYG field is non-repeatable

### ISSUE THREAD

**Issue by mikeselander** [humanmade/Custom-Meta-Boxes#381]
Repeating the WYSIWYG field doesn't work properly. We should either disallow the field from being repeatable or attempt to make it work as a repeatable. I'm leaning towards just disabling it from being repeatable but open to opinions if this is something that devs are desiring.

**Comment by ocean90** [comment]
@mikeselander Do you mean by "doesn't work properly" that the HTML source is printed? If so, that's caused by #364 and fb45336a01ef80e7a153ba24f4a48829b5890ed7. The editor markup is now escaped because of `esc_js()`, see https://github.com/humanmade/Custom-Meta-Boxes/commit/fb45336a01ef80e7a153ba24f4a48829b5890ed7#diff-2cb1e189aa9434d77fe7da9f3eb9b3c3R1022

I think this line should be changed to make use of `json_encode()`.

```diff
-  cmb_wysiwyg_editors.<?php echo esc_js( $field_id ); ?> = '<?php echo esc_js( $editor ); ?>';
+  cmb_wysiwyg_editors.<?php echo esc_js( $field_id ); ?> = <?php echo json_encode( $editor ); ?>;
```

Thoughts?

**Comment by mikeselander** [comment]
Ah, cheers @ocean90 - that makes my job of fixing this easier :)

That does indeed look like the wrong escaping being added there, good catch!
