### ISSUE TITLE
get 500 error

### ISSUE THREAD

**Issue by kostar** [humanmade/Custom-Meta-Boxes#436]
After installation and addition of `require_once( 'Custom-Meta-Boxes/custom-meta-boxes.php' )` to theme's function.php  I get 500 error. WP not working anymore. Is there a ready to use gmap?

**Comment by mikeselander** [comment]
Heya @kostar 👋

Can you provide me some more information on your setup so that I can help you diagnose this?

 - What is the error text that you're receiving?
 - Where is HMCMB located in relation to your functions.php file
 - What version of HMCMB are you running?
 - What version of PHP are you running? 

Thanks!

**Comment by kostar** [comment]
php 7.0.21 , master, error: require_once( 'Custom-Meta-Boxes/custom-meta-boxes.php' )
Perhaps I missed something in your instructions manual.
I can give you access to my webserver and you can look at it yourself :) If you want to.

**Comment by mikeselander** [comment]
@kostar it sounds to me like the HMCMB folder is not located in the place that you're trying to reference from `functions.php`. The paths must match exactly to the path you're inputting into that requires statement.

**Comment by ajitbohra** [comment]
@kostar hope its working fine?

**Comment by mikeselander** [comment]
Closing this issue as I believe this is a file issue. Feel free to re-open if necessary @kostar
